version: "3.9"

services:
  user-service:
    image: mojtaba2422/ecommerce-user-service:latest
    # build: .
    container_name: ecommerce-user-service
    ports:
      - "4000:4000"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ecommerce-config-server:8888
      - EUREKA_SERVER_URL=http://ecommerce-eureka-server:9999/eureka
      - GOOGLE_CLIENT_ID=your-client-id
      - GOOGLE_CLIENT_SECRET=your-client-secret
      - GITHUB_CLIENT_ID=your-client-id
      - GITHUB_CLIENT_SECRET=your-client-secret
      - DB_HOST=ecommerce-postgres-server
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER_NAME=test@gmail.com
      - MAIL_PASSWORD=xxxx xxxx xxxx xxxx
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge
    external: true
