spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
    label: master
    name: user-service
    fail-fast: true